# Auto-update versi dari Maven POM
version=${app.version}

# Konfigurasi Database
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/db_reservasi_hotel?useSSL=false&serverTimezone=Asia/Jakarta
db.user=root
db.password=