/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author RedmiBook 15
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */

    public Dashboard() {
        // Melakukan inisialisasi komponen GUI (Hanya boleh dipanggil satu kali di awal)
        initComponents();
        
        // 1. MENAMPILKAN TEKS SAMBUTAN USER
        lblWelcome.setText("Selamat Datang, " + utils.UserSession.getNamaLengkap());
        
        // 2. LOGIKA BACA VERSI OTOMATIS DARI MAVEN (app.properties)
        String versiAplikasi = "v1.0"; 
        try {
            java.io.InputStream is = getClass().getClassLoader().getResourceAsStream("app.properties");
            if (is != null) {
                java.util.Properties p = new java.util.Properties();
                p.load(is);
                versiAplikasi = p.getProperty("version");
            }
        } catch (Exception e) {
            utils.LogHelper.error("Gagal membaca file konfigurasi versi: " + e.getMessage());
            System.out.println("Gagal baca versi: " + e.getMessage());
        }
        
        // Memasang nomor versi dinamis ke judul title bar aplikasi
        setTitle("Dashboard - Manajemen Hotel (" + versiAplikasi + ")");
        
        // 3. MEMANGGIL STATISTIK KAMAR REAL-TIME
        loadStatistik(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        btnTipeKamar = new javax.swing.JButton();
        btnKamar = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        lblTersedia = new javax.swing.JLabel();
        lblTerisi = new javax.swing.JLabel();
        lblPerbaikan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblWelcome.setText("Selamat Datang, Admin");

        btnTipeKamar.setText("Master Tipe Kamar.");
        btnTipeKamar.addActionListener(this::btnTipeKamarActionPerformed);

        btnKamar.setText("Master Data Kamar.");
        btnKamar.addActionListener(this::btnKamarActionPerformed);

        btnLogout.setBackground(new java.awt.Color(255, 51, 51));
        btnLogout.setText("Logout.");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        lblTotal.setText("Total Kamar: -");

        lblTersedia.setForeground(new java.awt.Color(102, 255, 0));
        lblTersedia.setText("Kamar Tersedia: -");

        lblTerisi.setForeground(new java.awt.Color(255, 51, 51));
        lblTerisi.setText("Kamar Terisi: -");

        lblPerbaikan.setForeground(new java.awt.Color(255, 153, 51));
        lblPerbaikan.setText("Sedang Perbaikan: -");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(lblWelcome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTipeKamar)
                                .addGap(18, 18, 18)
                                .addComponent(btnKamar)
                                .addGap(47, 47, 47)
                                .addComponent(btnLogout))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTotal)
                                    .addComponent(lblTersedia))
                                .addGap(111, 111, 111)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPerbaikan)
                                    .addComponent(lblTerisi))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblWelcome)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(lblTerisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTersedia)
                    .addComponent(lblPerbaikan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTipeKamar)
                    .addComponent(btnKamar)
                    .addComponent(btnLogout))
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        utils.UserSession.logout(); 
        new Login().setVisible(true); 
        this.dispose(); 
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnTipeKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipeKamarActionPerformed
        // TODO add your handling code here:
        new DataTipeKamar().setVisible(true);
    }//GEN-LAST:event_btnTipeKamarActionPerformed

    
    
    private void btnKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKamarActionPerformed
        // TODO add your handling code here:
        new DataKamar().setVisible(true);
    }//GEN-LAST:event_btnKamarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void loadStatistik() {
        try {
            dao.KamarDAO kamarDao = new dao.KamarDAO();
            
            // Menarik data statistik real-time dari database
            int total = kamarDao.getTotalKamar();
            int tersedia = kamarDao.getJumlahKamarByStatus("tersedia");
            int terisi = kamarDao.getJumlahKamarByStatus("terisi");
            int perbaikan = kamarDao.getJumlahKamarByStatus("perbaikan");
            
            // Memasang hasil perhitungan ke komponen label di layar
            lblTotal.setText("Total Seluruh Kamar: " + total);
            lblTersedia.setText("Siap Huni (Tersedia): " + tersedia);
            lblTerisi.setText("Sedang Disewa (Terisi): " + terisi);
            lblPerbaikan.setText("Dalam Perbaikan: " + perbaikan);
            
        } catch (Exception e) {
            utils.LogHelper.error("Gagal memuat statistik dashboard: " + e.getMessage());
            System.out.println("Gagal memuat statistik: " + e.getMessage());
        }
    }
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if (utils.UserSession.isLogin()) {
                    new Dashboard().setVisible(true); 
                } else {
                    new Login().setVisible(true); 
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKamar;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnTipeKamar;
    private javax.swing.JLabel lblPerbaikan;
    private javax.swing.JLabel lblTerisi;
    private javax.swing.JLabel lblTersedia;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
