/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author RedmiBook 15
 */
public class DataKamar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DataKamar.class.getName());

    /**
     * Creates new form DataKamar
     */
    public DataKamar() {
        initComponents();
        loadTipeKamarComboBox(); 
        loadDataTabel();         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        cmbTipe = new javax.swing.JComboBox<>();
        txtKapasitas = new javax.swing.JTextField();
        txtLantai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFasilitas = new javax.swing.JTextArea();
        txtHarga = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelKamar = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NPM: 202343500303 | Nama: Rizki Fadhilah.");

        jLabel2.setText("Kode Kamar:");

        jLabel3.setText("Tipe Kamar:");

        jLabel4.setText("Kapasitas:");

        jLabel5.setText("Lantai:");

        jLabel6.setText("Fasilitas:");

        jLabel7.setText("Harga per Malam:");

        jLabel8.setText("Status:");

        cmbTipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtFasilitas.setColumns(20);
        txtFasilitas.setRows(5);
        jScrollPane1.setViewportView(txtFasilitas);

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tersedia", "terisi", "perbaikan" }));

        tabelKamar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelKamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKamarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelKamar);

        btnSave.setText("Save");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        Back.setText("Back");
        Back.addActionListener(this::BackActionPerformed);

        jButton1.setText("Export Data");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        jLabel9.setText("Cari Kamar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtLantai, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbTipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(5, 5, 5)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtCari, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1)
                                        .addGap(20, 20, 20))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Back)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLantai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(Back)
                    .addComponent(jButton1))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            if (txtKode.getText().trim().isEmpty() || txtKapasitas.getText().trim().isEmpty() || 
                txtLantai.getText().trim().isEmpty() || txtHarga.getText().trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Harap lengkapi semua data kamar!");
                return;
            }

            dao.KamarDAO kamarDao = new dao.KamarDAO();
            
            // Validasi Duplikat lewat DAO
            if (kamarDao.cekKodeKamar(txtKode.getText())) {
                javax.swing.JOptionPane.showMessageDialog(this, "Kode Kamar '" + txtKode.getText() + "' sudah ada!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            // MENGAMBIL ID TIPE KAMAR DARI DATABASE BERDASARKAN PILIHAN COMBOBOX
            dao.TipeKamarDAO tipeDao = new dao.TipeKamarDAO();
            int idTipe = tipeDao.getIdTipeByNama(cmbTipe.getSelectedItem().toString());
            
            if (idTipe == 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih tipe kamar yang valid!");
                return;
            }

            int kapasitas = Integer.parseInt(txtKapasitas.getText());
            int lantai = Integer.parseInt(txtLantai.getText());
            int harga = Integer.parseInt(txtHarga.getText());

            // Eksekusi Simpan Data lewat DAO (Sekarang menggunakan idTipe)
            kamarDao.insert(
                txtKode.getText(),
                idTipe,
                kapasitas,
                lantai,
                txtFasilitas.getText(),
                harga,
                cmbStatus.getSelectedItem().toString()
            );
            
            javax.swing.JOptionPane.showMessageDialog(this, "Data Kamar Berhasil Disimpan!");
            utils.LogHelper.info("Berhasil menyimpan data kamar baru: " + txtKode.getText());
            
            loadDataTabel(); 
            bersihkanForm(); 
            
        } catch (NumberFormatException nfe) {
            javax.swing.JOptionPane.showMessageDialog(this, "Kapasitas, Lantai, dan Harga harus berupa angka!", "Error Input", javax.swing.JOptionPane.ERROR_MESSAGE);
            utils.LogHelper.error("Error Format Angka di form kamar: " + nfe.getMessage());
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error Save: " + e.getMessage());
            utils.LogHelper.error("Error Save Kamar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        try {
            dao.KamarDAO kamarDao = new dao.KamarDAO();
            
            // MENGAMBIL ID TIPE KAMAR DARI DATABASE BERDASARKAN PILIHAN COMBOBOX
            dao.TipeKamarDAO tipeDao = new dao.TipeKamarDAO();
            int idTipe = tipeDao.getIdTipeByNama(cmbTipe.getSelectedItem().toString());
            
            if (idTipe == 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih tipe kamar yang valid!");
                return;
            }

            int kapasitas = Integer.parseInt(txtKapasitas.getText());
            int lantai = Integer.parseInt(txtLantai.getText());
            int harga = Integer.parseInt(txtHarga.getText());

            // Eksekusi Update Data lewat DAO (Sekarang menggunakan idTipe)
            kamarDao.update(
                txtKode.getText(),
                idTipe,
                kapasitas,
                lantai,
                txtFasilitas.getText(),
                harga,
                cmbStatus.getSelectedItem().toString()
            );
            
            javax.swing.JOptionPane.showMessageDialog(this, "Data Kamar Berhasil Diedit!");
            utils.LogHelper.info("Berhasil mengedit data kamar: " + txtKode.getText());
            
            loadDataTabel();
            bersihkanForm();
        } catch (NumberFormatException nfe) {
            javax.swing.JOptionPane.showMessageDialog(this, "Kapasitas, Lantai, dan Harga harus angka!", "Error Input", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error Edit: " + e.getMessage());
            utils.LogHelper.error("Error Edit Kamar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin hapus kamar " + txtKode.getText() + "?", "Konfirmasi", javax.swing.JOptionPane.YES_NO_OPTION);
        if (konfirmasi == 0) {
            try {
                dao.KamarDAO kamarDao = new dao.KamarDAO();
                kamarDao.delete(txtKode.getText());
                
                javax.swing.JOptionPane.showMessageDialog(this, "Data Kamar Berhasil Dihapus!");
                utils.LogHelper.info("Berhasil menghapus data kamar: " + txtKode.getText());
                
                loadDataTabel();
                bersihkanForm();
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error Delete: " + e.getMessage());
                utils.LogHelper.error("Error Delete Kamar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tabelKamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKamarMouseClicked
        // TODO add your handling code here:
        int baris = tabelKamar.getSelectedRow();
        if(baris != -1) {
            txtKode.setText(tabelKamar.getValueAt(baris, 0).toString());
            cmbTipe.setSelectedItem(tabelKamar.getValueAt(baris, 1).toString());
            txtKapasitas.setText(tabelKamar.getValueAt(baris, 2).toString());
            txtLantai.setText(tabelKamar.getValueAt(baris, 3).toString());
            txtFasilitas.setText(tabelKamar.getValueAt(baris, 4).toString());
            
            // TRIK GAIB: Mengembalikan format "Rp 450.000" menjadi angka murni "450000"
            // Sintaks regex [^0-9] artinya: Hapus semua karakter yang BUKAN angka 0 sampai 9
            String hargaRupiah = tabelKamar.getValueAt(baris, 5).toString();
            String hargaMurni = hargaRupiah.replaceAll("[^0-9]", ""); 
            txtHarga.setText(hargaMurni);
            
            cmbStatus.setSelectedItem(tabelKamar.getValueAt(baris, 6).toString());
        }
    }//GEN-LAST:event_tabelKamarMouseClicked

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        this.dispose(); 
    }//GEN-LAST:event_BackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            
            javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
            fileChooser.setDialogTitle("Simpan Data Export");
            int userSelection = fileChooser.showSaveDialog(this);
            
            if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
                java.io.File fileToSave = fileChooser.getSelectedFile();
                
                java.io.FileWriter fw = new java.io.FileWriter(fileToSave + ".csv");
                java.io.BufferedWriter bw = new java.io.BufferedWriter(fw);

                
                bw.write("Kode Kamar,Tipe,Kapasitas,Lantai,Fasilitas,Harga,Status");
                bw.newLine();

                
                for (int i = 0; i < tabelKamar.getRowCount(); i++) {
                    for (int j = 0; j < tabelKamar.getColumnCount(); j++) {
                        
                        bw.write("\"" + tabelKamar.getValueAt(i, j).toString() + "\"");
                        if (j < tabelKamar.getColumnCount() - 1) {
                            bw.write(",");
                        }
                    }
                    bw.newLine();
                }
                bw.close();
                fw.close();
                
                javax.swing.JOptionPane.showMessageDialog(this, "Data Berhasil Diexport ke:\n" + fileToSave.getAbsolutePath() + ".csv");
                utils.LogHelper.info("User berhasil melakukan export data kamar."); 
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal Export: " + ex.getMessage());
            utils.LogHelper.error("Gagal export data kamar: " + ex.getMessage()); 
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        // TODO add your handling code here:
        String keyword = txtCari.getText();
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(new String[]{"Kode", "Tipe", "Kapasitas", "Lantai", "Fasilitas", "Harga", "Status"}, 0);
        
        try {
            dao.KamarDAO kamarDao = new dao.KamarDAO();
            // Memanggil fungsi search yang baru saja kita buat
            java.util.List<Object[]> listKamar = kamarDao.searchKamar(keyword);
            
            // Jangan lupa pasang lagi format Rupiahnya agar tabel pencarian tetap cantik!
            java.text.NumberFormat formatRupiah = java.text.NumberFormat.getInstance(new java.util.Locale("id", "ID"));
            
            for (Object[] row : listKamar) {
                int hargaAsli = Integer.parseInt(row[5].toString());
                row[5] = "Rp " + formatRupiah.format(hargaAsli);
                model.addRow(row);
            }
            tabelKamar.setModel(model);
        } catch(Exception e) { 
            utils.LogHelper.error("Error Live Search: " + e.getMessage());
        }
    }//GEN-LAST:event_txtCariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DataKamar().setVisible(true));
    }
    
private void loadTipeKamarComboBox() {
        try {
            cmbTipe.removeAllItems();
            cmbTipe.addItem("- Pilih Tipe -");
            
            // Memanggil data menggunakan DAO, tiada lagi raw SQL di sini!
            dao.TipeKamarDAO tipeDao = new dao.TipeKamarDAO();
            java.util.List<Object[]> listTipe = tipeDao.getAllTipeKamar();
            
            // Menggelung (loop) senarai dan memasukkannya ke dalam ComboBox
            for (Object[] row : listTipe) {
                // row[1] mewakili lajur 'nama_tipe'
                cmbTipe.addItem(row[1].toString());
            }
        } catch(Exception e) { 
            utils.LogHelper.error("Error load ComboBox Tipe Kamar: " + e.getMessage()); 
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat daftar tipe kamar!");
        }
    }

private void loadDataTabel() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(new String[]{"Kode", "Tipe", "Kapasitas", "Lantai", "Fasilitas", "Harga", "Status"}, 0);
        try {
            dao.KamarDAO kamarDao = new dao.KamarDAO();
            java.util.List<Object[]> listKamar = kamarDao.getAllKamar();
            
            // Format angka standar Indonesia
            java.text.NumberFormat formatRupiah = java.text.NumberFormat.getInstance(new java.util.Locale("id", "ID"));
            
            for (Object[] row : listKamar) {
                // Mencegat data harga di indeks ke-5 (0: kode, 1: tipe, 2: kap, 3: lan, 4: fas, 5: harga, 6: status)
                int hargaAsli = Integer.parseInt(row[5].toString());
                row[5] = "Rp " + formatRupiah.format(hargaAsli); // Mengubah 450000 menjadi Rp 450.000
                
                model.addRow(row);
            }
            tabelKamar.setModel(model);
        } catch(Exception e) { 
            utils.LogHelper.error("Error Load Data Tabel Kamar: " + e.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat data tabel kamar!");
        }
    }
    
    private void bersihkanForm() {
        txtKode.setText("");
        cmbTipe.setSelectedIndex(0);
        txtKapasitas.setText("");
        txtLantai.setText("");
        txtFasilitas.setText("");
        txtHarga.setText("");
        cmbStatus.setSelectedIndex(0);
        txtKode.requestFocus(); // Kembalikan kursor ke form atas
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JComboBox<String> cmbTipe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelKamar;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextArea txtFasilitas;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKapasitas;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtLantai;
    // End of variables declaration//GEN-END:variables
}
